name: bbrbet
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  location: ^5.0.3
  get: ^5.0.0-release-candidate-5
  google_fonts: ^5.1.0
  flutter_date_difference: ^1.0.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  http: ^1.2.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/

